
cp '1.com.h.src' '/usr/src/include/minix/com.h'
cp '2.syslib.h.src' '/usr/src/include/minix/syslib.h'
cp '3.main.c.src' '/usr/src/kernel/main.c'
cp '4.proc.c.src' '/usr/src/kernel/proc.c'
cp '5.proc.h.src' '/usr/src/kernel/proc.h'
cp '6.do_getinfo.c.src' '/usr/src/kernel/system/do_getinfo.c'
cp '7.dmp.c.src' '/usr/src/servers/is/dmp.c'
cp '8.dmp_kernel.c.src' '/usr/src/servers/is/dmp_kernel.c'
cp '9.proto.h.src' '/usr/src/servers/is/proto.h'
